from dataclasses import dataclass
from typing import Callable

from ..domain.models import Reply
from ..gameplay import adventure, cultivation, duels, economy, equipment, forging, identity, information, pets, quests, skills
from ..gameplay import crafting, expeditions, lineage
from ..gameplay.teams import management, party, requests
from .context import Context


@dataclass(frozen=True)
class Command:
    handler: Callable[[Context, str], Reply]
    arguments: bool = False


ACTIONS = {
    "help": Command(information.help_game),
    "identity": Command(identity.profile),
    "dao_name": Command(identity.rename, True),
    "status": Command(information.status),
    "catalog": Command(information.catalog, True),
    "rank": Command(information.rank),
    "pvp_rank": Command(information.pvp_rank),
    "adopt": Command(pets.adopt, True),
    "summon": Command(pets.summon, True),
    "pet_list": Command(pets.pet_list, True),
    "switch": Command(pets.switch, True),
    "rename": Command(pets.rename, True),
    "sign": Command(economy.sign),
    "bag": Command(economy.bag),
    "shop": Command(economy.shop, True),
    "buy": Command(economy.buy, True),
    "use": Command(economy.use, True),
    "feed": Command(economy.feed),
    "train": Command(cultivation.train),
    "breakthrough": Command(cultivation.breakthrough, True),
    "evolve": Command(cultivation.evolve),
    "lineage_catalog": Command(lineage.catalog, True),
    "lineage_choose": Command(lineage.choose, True),
    "explore": Command(adventure.explore),
    "dungeons": Command(adventure.dungeons, True),
    "challenge": Command(adventure.challenge, True),
    "quests": Command(quests.quests),
    "claim": Command(quests.claim, True),
    "expedition_catalog": Command(expeditions.catalog, True),
    "expedition_start": Command(expeditions.start, True),
    "expedition_status": Command(expeditions.status, True),
    "expedition_claim": Command(expeditions.claim, True),
    "expedition_cancel": Command(expeditions.cancel, True),
    "pvp": Command(duels.pvp, True),
    "spar": Command(duels.spar, True),
    "accept": Command(duels.accept),
    "reject": Command(duels.reject),
    "team_create": Command(party.create),
    "team_join": Command(requests.join, True),
    "team_invite": Command(requests.invite, True),
    "team_requests": Command(requests.inbox, True),
    "team_accept": Command(requests.accept, True),
    "team_reject": Command(requests.reject, True),
    "team_withdraw": Command(requests.withdraw, True),
    "team_status": Command(party.status, True),
    "team_ready": Command(party.ready),
    "team_unready": Command(party.unready),
    "team_leave": Command(management.leave),
    "team_kick": Command(management.kick, True),
    "team_transfer": Command(management.transfer, True),
    "team_disband": Command(management.disband),
    "team_challenge": Command(party.challenge, True),
    "equipment": Command(equipment.view, True),
    "equipment_catalog": Command(equipment.catalog, True),
    "unequip": Command(equipment.unequip, True),
    "enhance": Command(forging.enhance, True),
    "recipe_catalog": Command(crafting.catalog, True),
    "craft": Command(crafting.craft, True),
    "salvage": Command(crafting.salvage, True),
    "skills": Command(skills.view),
    "skill_catalog": Command(skills.catalog, True),
    "learn": Command(skills.learn, True),
    "equip_skill": Command(skills.equip, True),
    "unequip_skill": Command(skills.unequip, True),
}
COMMANDS = {
    "灵宠": "help", "灵宠帮助": "help", "我的道号": "identity", "灵宠道号": "dao_name", "我的灵宠": "status",
    "灵宠图鉴": "catalog", "灵宠排行": "rank", "灵宠论剑榜": "pvp_rank",
    "灵宠领养": "adopt", "灵宠召唤": "summon", "灵宠列表": "pet_list", "灵宠切换": "switch",
    "灵宠改名": "rename", "灵宠签到": "sign", "灵宠背包": "bag", "灵宠商店": "shop",
    "灵宠购买": "buy", "灵宠使用": "use", "灵宠喂养": "feed", "灵宠修炼": "train",
    "灵宠突破": "breakthrough", "灵宠进化": "evolve", "灵宠历练": "explore",
    "灵宠秘境": "dungeons", "灵宠挑战": "challenge", "灵宠任务": "quests", "灵宠领奖": "claim",
    "灵宠委托": "expedition_catalog", "灵宠派遣": "expedition_start", "灵宠行程": "expedition_status",
    "灵宠归来": "expedition_claim", "灵宠召回": "expedition_cancel",
    "灵宠论剑": "pvp", "灵宠切磋": "spar", "灵宠应战": "accept", "灵宠拒战": "reject",
    "灵宠组队": "team_create", "灵宠入队": "team_join", "灵宠队伍": "team_status",
    "灵宠准备": "team_ready", "灵宠取消准备": "team_unready", "灵宠退队": "team_leave",
    "灵宠组队挑战": "team_challenge",
    "灵宠邀请": "team_invite", "灵宠队务": "team_requests",
    "灵宠队伍同意": "team_accept", "灵宠队伍拒绝": "team_reject", "灵宠队伍撤回": "team_withdraw",
    "灵宠踢人": "team_kick", "灵宠转让": "team_transfer", "灵宠解散": "team_disband",
    "灵宠装备": "equipment", "灵宠装备图鉴": "equipment_catalog", "灵宠卸装": "unequip",
    "灵宠强化": "enhance",
    "灵宠血脉": "lineage_catalog", "灵宠分支": "lineage_choose",
    "灵宠工坊": "recipe_catalog", "灵宠打造": "craft", "灵宠分解": "salvage",
    "灵宠技能": "skills", "灵宠技能图鉴": "skill_catalog", "灵宠学习": "learn",
    "灵宠携带": "equip_skill", "灵宠卸技": "unequip_skill",
}
