from dataclasses import dataclass
from typing import Callable

from ..domain.models import Reply
from ..gameplay import adventure, cultivation, economy, equipment, forging, identity, information, pets, quests, skills
from ..gameplay import companionship, crafting, expeditions, lineage, pve_stages
from ..gameplay import achievements, resonance
from ..gameplay import battle_records, help
from ..gameplay.arena import battles, matching, seasons
from ..gameplay.teams import management, party, requests
from .context import Context


@dataclass(frozen=True)
class Command:
    handler: Callable[[Context, str], Reply]
    arguments: bool = False
    registered: bool = True


ACTIONS = {
    "help": Command(help.help_game, True, registered=False),
    "identity": Command(identity.profile, registered=False),
    "dao_name": Command(identity.rename, True),
    "status": Command(information.status),
    "catalog": Command(information.catalog, True, registered=False),
    "rank": Command(information.rank, registered=False),
    "adventure_rank": Command(information.adventure_rank, registered=False),
    "pvp_rank": Command(seasons.rank, True, registered=False),
    "season": Command(seasons.status, True),
    "season_rewards": Command(seasons.catalog, True),
    "season_claim": Command(seasons.claim, True),
    "match": Command(matching.candidates, True),
    "adopt": Command(pets.adopt, True, registered=False),
    "summon": Command(pets.summon, True),
    "pet_list": Command(pets.pet_list, True),
    "pet_archive_list": Command(pets.archive_list, True),
    "pet_archive": Command(pets.archive, True),
    "pet_restore": Command(pets.restore, True),
    "switch": Command(pets.switch, True),
    "lineup": Command(pets.lineup, True),
    "sign": Command(economy.sign),
    "bag": Command(economy.bag),
    "shop": Command(economy.shop, True, registered=False),
    "buy": Command(economy.buy, True),
    "use": Command(economy.use, True),
    "feed": Command(economy.feed, True),
    "bond": Command(companionship.bond, True),
    "train": Command(cultivation.train, True),
    "co_train": Command(cultivation.co_train, True),
    "breakthrough": Command(cultivation.breakthrough, True),
    "evolve": Command(cultivation.evolve, True),
    "lineage_catalog": Command(lineage.catalog, True, registered=False),
    "lineage_choose": Command(lineage.choose, True),
    "explore": Command(adventure.explore, True, registered=False),
    "adventure_codex": Command(adventure.adventure_codex, True, registered=False),
    "dungeons": Command(adventure.dungeons, True, registered=False),
    "challenge": Command(adventure.challenge, True),
    "stage_catalog": Command(pve_stages.catalog, True, registered=False),
    "stage_challenge": Command(pve_stages.challenge, True),
    "achievements": Command(achievements.achievements, True, registered=False),
    "achievement_claim": Command(achievements.claim, True),
    "collection": Command(achievements.collection, True, registered=False),
    "resonance": Command(resonance.resonance, True),
    "team_stage_challenge": Command(pve_stages.team_challenge, True),
    "quests": Command(quests.quests),
    "claim": Command(quests.claim, True),
    "expedition_catalog": Command(expeditions.catalog, True, registered=False),
    "expedition_start": Command(expeditions.start, True),
    "expedition_status": Command(expeditions.status, True),
    "expedition_claim": Command(expeditions.claim, True),
    "expedition_cancel": Command(expeditions.cancel, True),
    "pvp": Command(battles.pvp, True),
    "spar": Command(battles.spar, True),
    "battle_reports": Command(battle_records.reports, True),
    "team_create": Command(party.create),
    "team_join": Command(requests.join, True),
    "team_invite": Command(requests.invite, True),
    "team_requests": Command(requests.inbox, True),
    "team_accept": Command(requests.accept, True),
    "team_reject": Command(requests.reject, True),
    "team_withdraw": Command(requests.withdraw, True),
    "team_status": Command(party.status, True),
    "team_ready": Command(party.ready),
    "team_unready": Command(party.unready),
    "team_leave": Command(management.leave),
    "team_kick": Command(management.kick, True),
    "team_transfer": Command(management.transfer, True),
    "team_disband": Command(management.disband),
    "team_challenge": Command(party.challenge, True),
    "equipment": Command(equipment.view, True),
    "equipment_sets": Command(equipment.sets, True, registered=False),
    "equipment_catalog": Command(equipment.catalog, True, registered=False),
    "unequip": Command(equipment.unequip, True),
    "enhance": Command(forging.enhance, True),
    "recipe_catalog": Command(crafting.catalog, True, registered=False),
    "craft": Command(crafting.craft, True),
    "salvage": Command(crafting.salvage, True),
    "skills": Command(skills.view),
    "skill_catalog": Command(skills.catalog, True, registered=False),
    "learn": Command(skills.learn, True),
    "equip_skill": Command(skills.equip, True),
    "unequip_skill": Command(skills.unequip, True),
}
COMMANDS = {
    "灵宠": "help", "灵宠帮助": "help", "我的信息": "identity", "灵宠道号": "dao_name",
    "我的灵宠": "status", "我的宠": "status",
    "灵宠图鉴": "catalog", "灵宠排行": "rank", "灵宠奇闻榜": "adventure_rank", "灵宠论剑榜": "pvp_rank",
    "灵宠赛季": "season", "灵宠赛季奖励": "season_rewards", "灵宠赛季领奖": "season_claim",
    "灵宠匹配": "match",
    "灵宠领养": "adopt", "灵宠召唤": "summon", "灵宠列表": "pet_list", "灵宠切换": "switch",
    "灵宠封存库": "pet_archive_list", "灵宠封存": "pet_archive", "灵宠复原": "pet_restore",
    "灵宠出战": "lineup", "灵宠阵容": "lineup", "灵宠签到": "sign", "灵宠背包": "bag", "灵宠商店": "shop",
    "灵宠购买": "buy", "灵宠使用": "use", "灵宠喂养": "feed", "灵宠互动": "bond", "灵宠修炼": "train",
    "灵宠合修": "co_train",
    "灵宠突破": "breakthrough", "灵宠进化": "evolve", "灵宠历练": "explore", "灵宠奇闻": "adventure_codex",
    "灵宠秘境": "dungeons", "灵宠挑战": "challenge", "灵宠任务": "quests", "灵宠领奖": "claim",
    "灵宠关卡": "stage_catalog", "灵宠挑战关卡": "stage_challenge",
    "灵宠组队关卡": "team_stage_challenge",
    "灵宠成就": "achievements", "灵宠成就领奖": "achievement_claim", "灵宠收集": "collection",
    "灵宠共鸣": "resonance",
    "灵宠委托": "expedition_catalog", "灵宠派遣": "expedition_start", "灵宠行程": "expedition_status",
    "灵宠归来": "expedition_claim", "灵宠召回": "expedition_cancel",
    "灵宠论剑": "pvp", "灵宠切磋": "spar",
    "灵宠战报": "battle_reports",
    "灵宠组队": "team_create", "灵宠入队": "team_join", "灵宠队伍": "team_status",
    "灵宠准备": "team_ready", "灵宠取消准备": "team_unready", "灵宠退队": "team_leave",
    "灵宠组队挑战": "team_challenge",
    "灵宠邀请": "team_invite", "灵宠队务": "team_requests",
    "灵宠队伍同意": "team_accept", "灵宠队伍拒绝": "team_reject", "灵宠队伍撤回": "team_withdraw",
    "灵宠踢人": "team_kick", "灵宠转让": "team_transfer", "灵宠解散": "team_disband",
    "灵宠装备": "equipment", "灵宠装备图鉴": "equipment_catalog", "灵宠卸装": "unequip",
    "灵宠套装": "equipment_sets",
    "灵宠强化": "enhance",
    "灵宠血脉": "lineage_catalog", "灵宠分支": "lineage_choose",
    "灵宠工坊": "recipe_catalog", "灵宠打造": "craft", "灵宠分解": "salvage",
    "灵宠技能": "skills", "灵宠技能图鉴": "skill_catalog", "灵宠学习": "learn",
    "灵宠携带": "equip_skill", "灵宠卸技": "unequip_skill",
}
